app:
  kafka:
    topics:
      trip-timing: trip-timing
      trip-update: trip-update
      trip-update-dlt: trip-update.DLT
      service-alert: service-alert
spring:
  application:
    name: transit-reliability-detector
  
  datasource:
    url: jdbc:postgresql://localhost:5432/transit_db
    username: transit_user
    password: transit_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      compression-type: lz4
      batch-size: 65536

      properties:
        linger.ms: 5
    consumer:
      group-id: transit-reliability-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.transit.reliability.model"



aws:
  region: us-east-2
  lambda:
    service-alert-function-name: mta-service-alert-processor
mta:
  realtime:
    feed-url: "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-ace"
    api-key: ""
    polling-interval: "60s"
    enabled: true
  service-alert:
    feed-url: "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-servicealerts"
    api-key: ""
    enabled: false
    polling-interval: "60s"
  alerts:
    feed-url: "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/camsys%2Fsubway-alerts.json"
    api-key: ""
    polling-interval: "60s"
    enabled: true

server:
  port: 8080
